//Stephen Strickland
//This Class updates and draws the board every N seconds that is determined by the Timer

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import javax.swing.Timer;

public class RatMap extends JPanel implements ActionListener {

	/**
	 * automatically generated by eclipse
	 */
	private static final long serialVersionUID = 1936823489214515340L;
	int ratRow, ratCol;
	Map map;

	RatMap()
	{
		map = new Map();
		//updates 60 times a second (monitor refresh rat in the US)
		Timer timer  = new Timer(16, this);
		timer.start();
	}

	public void paint(Graphics g) 
	{
		super.paint(g);

		for(int row = 0; row < 100; row++)
		{
			for(int col = 0; col < 100; col++)
			{
				if(map.getIndex(col, row) == 'w')
				{
					g.drawImage(map.getWall(), col*8, row*8, null);
				}

				if(map.getIndex(col, row) == 'p')
				{
					g.drawImage(map.getPath(), col*8, row*8, null);
				}

				if(map.getIndex(col, row) == 'o')
				{
					g.drawImage(map.getOut(), col*8, row*8, null);
				}
			}
		}

		g.drawImage(map.getRat(), ratRow*8, ratCol*8, null);

	}
	//all cleaned up. 
	public void newPosition(String position)
	{

		char[] pos = position.toCharArray();
		pos[4] = 'p';
		map.updateMaze(pos, ratRow, ratCol);
	}

	public void setRow(int i)
	{
		ratRow = i;
	}

	public void setCol(int i)
	{
		ratCol = i;
	}


	public void actionPerformed(ActionEvent e) {
		repaint();

	}

}
